# Generated by Django 3.2.15 on 2022-09-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarriageContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male_firstName', models.CharField(blank=True, max_length=200, null=True)),
                ('male_lastName', models.CharField(blank=True, max_length=200, null=True)),
                ('femaleFather_firstName', models.CharField(blank=True, max_length=200, null=True)),
                ('femaleFather_lastName', models.CharField(blank=True, max_length=200, null=True)),
                ('place', models.CharField(blank=True, max_length=200, null=True)),
                ('placeType', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarriageDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male_firstName', models.CharField(blank=True, max_length=200, null=True)),
                ('male_lastName', models.CharField(blank=True, max_length=200, null=True)),
                ('male_phoneNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('femaleFather_firstName', models.CharField(blank=True, max_length=200, null=True)),
                ('femaleFather_lastName', models.CharField(blank=True, max_length=200, null=True)),
                ('weekDay', models.CharField(blank=True, max_length=200, null=True)),
                ('hijriDay', models.CharField(blank=True, max_length=200, null=True)),
                ('hijriMonth', models.CharField(blank=True, max_length=200, null=True)),
                ('hijriYear', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField()),
                ('place', models.CharField(blank=True, max_length=200, null=True)),
                ('placeType', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('locationUrl', models.URLField(max_length=128, unique=True)),
                ('image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
            ],
        ),
    ]
