# Generated by Django 3.2.15 on 2022-09-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marriagecontract',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marriagedate',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
